### ISSUE TITLE
Question about LCD Display

### ISSUE THREAD

**Issue by artvel** [mafredri/asustor_as-6xxt#1]
Hi @mafredri

Great job!
Any progress on the LCD display so far?

**Comment by mafredri** [comment]
Thanks. Yeah I believe I've captured most of the functionality. Writing message(s), clearing the screen, turning it on/off and reading button presses. (It can also be turned off by changing a gpio output on the it87 chip). I, however, never got around to finishing the program and actually making it useful 😄.

Would you mind telling me what your interest in it is? Are you running a custom Linux distro on your Asustor? Would you simply like it to be more powerful? Do you have a specific feature in mind?

**Comment by artvel** [comment]
Thanks for your quick response!
Yeah, I am using it with debian and other tools on top of it. I would love to make it more powerful. 
Wanted to try to create a simple library for the display. So far, I was able to achieve that goal with a Qnap TVS-x72XT but not with the Asustor.

**Comment by mafredri** [comment]
Cool. I haven't really touched this code since 2018, but I'll try to clean it up a bit and push it to GitHub tomorrow. It's currently implemented like a client/server where the server is dumb to allow running it on the NAS and do quick iteration on the client (much good that did me 😅).

**Comment by artvel** [comment]
Wow, that would be awesome.
Thanks a lot in advance.

**Comment by artvel** [comment]
Btw, I love Go. My tools are written in Go too.
Don't clean up to much just because of me.. I could clean it up too and share it afterwards..
Can't wait to play around with your solution.

**Comment by mafredri** [comment]
Nice, Go is pretty awesomely, yeah ☺️. Didn’t get around to this yesterday but I’ll make a new attempt tonight. Tomorrow at the latest. Not planning to delay it until it’s perfect but it was in the middle of a refactor so need to pick up the pieces. 😅

That said, your timing was pretty good because it had been on my mind this week before you asked, so it inspired me a bit. But anyway, like I said, won’t polish it too much, just want the code to be clear enough to pick up on wth is going on.

**Comment by mafredri** [comment]
Sorry I couldn't do this sooner @artvel, but here you go: https://github.com/mafredri/lcm. I added a README to help make sense of the project structure.

PRs are very much welcome! 😄

**Comment by artvel** [comment]
Wow! This is huge. Didn't expect that much code end structure :-)
Looks nice, great job.
Will let you know if it works for me soon.
Hope I can return the favor if it does.. very nice!

**Comment by mafredri** [comment]
Thanks! I don't think they've updated the protocol since the original NASes but you never know. At least it works on both AS604T and AS6204T for me.

One thing to keep in mind if you run into issues:
- `(*LCM).Sync` should probably be run on startup until the OK response is received (`0xf1011103` including checksum), and possibly at other times too if a communication errors are repeated
- Command messages (e.g. updating display text) should probably be repeated a few times unless the OK response is received (`0xf101270019` including checksum), the ASUSTOR daemon seems to wait 100 ms between tries. And if it doesn't work after like 5 tries it probably won't clear itself up, so then Sync might help

These are just some observations, and you can look at some of the logs I've intercepted from the ASUSTOR daemon to see if those help, if you run into any trouble (linked them in the readme).

**Comment by artvel** [comment]
Works great! I have Asustor AS6404T.
I think, I had some issues that could be related to Sync because I had to try it a couple of times und it finally worked.

Anyways, as I already said more than I expected!
Really great job! Didn't expect to see a custom message on this display so soon.

**Comment by artvel** [comment]
I managed to implement a stable version based on the information/source you provided incl. button handling.
Need to improve the quality a bit. But I am not sure if a PR would make sense. Up to you to decide.

I have a generic interface for displays like this and the asustor implementation is currently the second one. You are using it somehow differently.
So this is my interface, it is not perfect but it does already more than I need. Would it suit your needs?
```Go
type (
	LCD interface {
		Listen(l func(btn int, released bool) bool)
		Enable(yes bool) error
		Write(line Line, text string) error
		Open() error
		Close() error
	}
	Line int
	dummy struct{}


func (d *dummy) Listen(l func(btn int, released bool) bool) {}
func (d *dummy) Enable(yes bool) error                      { return nil }
func (d *dummy) Write(line Line, text string) error         { return nil }
func (d *dummy) Open() error                                { return nil }
func (d *dummy) Close() error                               { return nil }
)
```

I use the dummy in case there is no implementation for a display to not break the general usage.

Let me know what you think.

**Comment by mafredri** [comment]
That's awesome, I'm stoked you managed to make use of it!

Regarding the project, I think what I'd be looking for is improvements that make the communication more robust and/or improvements to the `lcm` API to cover more use-cases, but I think the interface is well suited for a separate wrapper package that calls the `lcm` methods to expose the unified LCD API. Alternatively if there's a widely used standard API (for LCDs) it could be a good fit for the project. Btw, if you've had to make changes to the `lcm` package to accommodate the interface, it'd be interesting to see if we can make some general tweaks to the `lcm` API to make it more suited for the use case.

Thanks for reporting back on your results! ☺️

**Comment by artvel** [comment]
Yeah, I would have done it sooner. But didn't know how to start the communication from scratch with zero commands. Btw. where did you find those command?

My results are pretty slight compared to your delivery.
```
-dispaly(package):
---asustor.go // asustor impl.
---qnap.go //qnap impl.
---generic.go //interface...
```
How do you want me to share it?
Could create a new repository and you could check if you can use it for your purposes or if it is trash :-)

**Comment by artvel** [comment]
pushed it here:
https://github.com/artvel/display

**Comment by mafredri** [comment]
> @mafredri I fixed the sync issue almost like you suggested here: [#1 (comment)](https://github.com/mafredri/asustor_as-6xxt/issues/1#issuecomment-851050407)

Glad it worked out 👍🏻.

Could you btw include the MIT license from [mafredri/lcm](https://github.com/mafredri/lcm) for the relevant parts that were copied/based on the project? I had originally thought you would use `lcm` as a library in your project and call its functions, but the way you implemented it works fine too, of course.

It's great that you published your project, hope it can be beneficial for some other people too. ☺️

> Yeah, I would have done it sooner. But didn't know how to start the communication from scratch with zero commands. Btw. where did you find those command?

By intercepting communication between the LCM daemon on ADM and the screen, and reverse-engineering the protocol.  Took a while to figure everything out. 😄
